import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from "next/link";
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Learning Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Elearning site
        </h1>

        <div className={styles.grid}>
          <Link href="/learn/next">
              <h2 className={inter.className}>
                Learn Next.js <span>-&gt;</span>
              </h2>
          </Link>

          <Link href="/learn/react">
              <h2 className={inter.className}>
                Learn React <span>-&gt;</span>
              </h2>
          </Link>

          <Link href="/learn/angular">
              <h2 className={inter.className}>
                Learn Angular <span>-&gt;</span>
              </h2>
          </Link>

          <Link href="/learn/vue">
              <h2 className={inter.className}>
                Learn Vue <span>-&gt;</span>
              </h2>
          </Link>
        </div>
      </main>
    </>
  )
}
